# Generated by Django 3.0.3 on 2020-08-11 04:38

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200810_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '128x128', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to='media-root/'),
        ),
    ]
