# Generated by Django 3.0.3 on 2020-08-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200810_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='width_field',
        ),
    ]
