# Generated by Django 3.0.3 on 2020-08-09 18:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(choices=[('$500', '$500'), ('$750', '$750'), ('$1000', '$1000'), ('$1,500', '$1,500'), ('$2,000', '$2,000'), ('$3,000', '$3,000'), ('$5,000', '$5,000'), ('$7,000', '$7000'), ('$10,000', '$10,000')], help_text='Select amount to deposit', max_length=25)),
                ('payment_option', models.CharField(help_text='Select payment option', max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
