# Generated by Django 3.0.3 on 2021-01-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200901_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.CharField(choices=[('$300', '$300'), ('$500', '$500'), ('$750', '$750'), ('$1000', '$1000'), ('$1,500', '$1,500'), ('$2,000', '$2,000'), ('$3,000', '$3,000'), ('$5,000', '$5,000'), ('$7,000', '$7000'), ('$10,000', '$10,000')], help_text='Select amount to deposit', max_length=25),
        ),
    ]
