# Generated by Django 3.0.3 on 2020-08-12 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200811_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='IBAN_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(code='invalid_characters', message='Must be numeric', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='swift_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
