# Generated by Django 3.0.3 on 2020-08-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_details', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
