# Generated by Django 3.0.3 on 2020-09-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_details', '0005_banktransfer_routing_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransfer',
            name='routing_number',
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='recipient_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='sort_code',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
